include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    unnecessary_lambdas: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore