import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:tudo_em_casa/core/services/export/data_export_service.dart';
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tudo_em_casa/core/database/app_database.dart';
import 'package:tudo_em_casa/core/services/import/data_import_service.dart';
import 'package:tudo_em_casa/features/categories/data/models/category_model.dart';
import 'package:tudo_em_casa/features/categories/data/repositories/category_repository.dart';
import 'package:tudo_em_casa/features/lots/data/models/lot_model.dart';
import 'package:tudo_em_casa/features/lots/data/repositories/lot_repository.dart';
import 'package:tudo_em_casa/features/product_types/data/models/product_type_model.dart';
import 'package:tudo_em_casa/features/product_types/data/repositories/product_type_repository.dart';
import 'package:tudo_em_casa/features/products/data/models/product_model.dart';
import 'package:tudo_em_casa/features/products/data/repositories/product_repository.dart';
import 'package:tudo_em_casa/features/units/data/models/unit_model.dart';
import 'package:tudo_em_casa/features/units/data/repositories/unit_repository.dart';

class FailingUnitRepository extends UnitRepository {
  FailingUnitRepository(super.db);

  @override
  Future<void> insertUnits(List<UnitModel> units) async {
    throw StateError('Failed to import units');
  }
}

ProductRepository createProductRepository(AppDatabase database) {
  return ProductRepository(database, LotRepository(database));
}

void main() {
  test('returns null when the user cancels file selection', () async {
    final database = AppDatabase.forTesting(NativeDatabase.memory());
    addTearDown(database.close);

    final service = DataImportService(
      database: database,
      categoryRepository: CategoryRepository(database),
      productTypeRepository: ProductTypeRepository(database),
      unitRepository: UnitRepository(database),
      productRepository: createProductRepository(database),
      pickBackupFile: ({dialogTitle}) async => null,
    );

    final payload = await service.pickBackupFile();

    expect(payload, isNull);
  });

  test('rejects invalid backup files before import', () async {
    final database = AppDatabase.forTesting(NativeDatabase.memory());
    addTearDown(database.close);

    final service = DataImportService(
      database: database,
      categoryRepository: CategoryRepository(database),
      productTypeRepository: ProductTypeRepository(database),
      unitRepository: UnitRepository(database),
      productRepository: createProductRepository(database),
      pickBackupFile: ({dialogTitle}) async {
        return Uint8List.fromList(utf8.encode('{"schemaVersion":2}'));
      },
    );

    expect(service.pickBackupFile(), throwsA(isA<DataImportException>()));
  });

  test('imports a backup generated by the export service', () async {
    final exportDirectory = await Directory.systemTemp.createTemp(
      'tudo_em_casa_import_roundtrip_test',
    );
    addTearDown(() async {
      if (await exportDirectory.exists()) {
        await exportDirectory.delete(recursive: true);
      }
    });

    final exportDatabase = AppDatabase.forTesting(NativeDatabase.memory());
    addTearDown(exportDatabase.close);

    final exportCategoryRepository = CategoryRepository(exportDatabase);
    final exportProductTypeRepository = ProductTypeRepository(exportDatabase);
    final exportUnitRepository = UnitRepository(exportDatabase);
    final exportProductRepository = createProductRepository(exportDatabase);

    final categoryId = await exportCategoryRepository.createCategory('Pantry');
    final unitId = await exportUnitRepository.createUnit('Kilogram', 'kg');
    final productTypeId = await exportProductTypeRepository.createProductType(
      'Rice',
      categoryId,
    );
    await exportProductRepository.createProduct(
      ProductModel(
        id: 0,
        name: 'Rice',
        productTypeId: productTypeId,
        lots: [
          LotModel(
            id: 0,
            productId: 0,
            unitId: unitId,
            quantity: 2.5,
            expirationDate: DateTime(2026, 1, 1),
          ),
        ],
      ),
    );

    final exportService = DataExportService(
      categoryRepository: exportCategoryRepository,
      productTypeRepository: exportProductTypeRepository,
      unitRepository: exportUnitRepository,
      productRepository: exportProductRepository,
      saveFile: ({dialogTitle, fileName, bytes}) async {
        final outputFile = File('${exportDirectory.path}/$fileName');
        await outputFile.writeAsBytes(bytes!);
        return outputFile.path;
      },
    );

    final exportFilePath = await exportService.exportData();
    final exportBytes = await File(exportFilePath!).readAsBytes();

    await exportDatabase.close();

    final importDatabase = AppDatabase.forTesting(NativeDatabase.memory());
    addTearDown(importDatabase.close);

    final importService = DataImportService(
      database: importDatabase,
      categoryRepository: CategoryRepository(importDatabase),
      productTypeRepository: ProductTypeRepository(importDatabase),
      unitRepository: UnitRepository(importDatabase),
      productRepository: createProductRepository(importDatabase),
      pickBackupFile: ({dialogTitle}) async => Uint8List.fromList(exportBytes),
    );

    final payload = await importService.pickBackupFile();
    expect(payload, isNotNull);

    await importService.importBackup(payload!);

    final importedCategories = await CategoryRepository(
      importDatabase,
    ).getCategories();
    final importedProductTypes = await ProductTypeRepository(
      importDatabase,
    ).getProductTypes();
    final importedUnits = await UnitRepository(importDatabase).getUnits();
    final importedProducts = await ProductRepository(
      importDatabase,
      LotRepository(importDatabase),
    ).getProducts();

    expect(importedCategories.single.name, 'Pantry');
    expect(importedProductTypes.single.name, 'Rice');
    expect(importedUnits.single.symbol, 'kg');
    expect(importedProducts.single.lots, hasLength(1));
    expect(importedProducts.single.lots!.single.quantity, 2.5);
  });

  test(
    'imports a JSON backup transactionally and replaces current data',
    () async {
      final database = AppDatabase.forTesting(NativeDatabase.memory());
      addTearDown(database.close);

      final categoryRepository = CategoryRepository(database);
      final productTypeRepository = ProductTypeRepository(database);
      final unitRepository = UnitRepository(database);
      final productRepository = createProductRepository(database);

      final originalCategoryId = await categoryRepository.createCategory('Old');
      final originalUnitId = await unitRepository.createUnit('Old Unit', 'ou');
      final originalProductTypeId = await productTypeRepository
          .createProductType('Old Type', originalCategoryId);
      await productRepository.createProduct(
        ProductModel(
          id: 0,
          name: 'Old Product',
          productTypeId: originalProductTypeId,
          lots: [
            LotModel(
              id: 0,
              productId: 0,
              unitId: originalUnitId,
              quantity: 1,
              expirationDate: null,
            ),
          ],
        ),
      );

      final backupPayload = BackupImportPayload(
        categories: [CategoryModel(id: 10, name: 'Pantry')],
        productTypes: [ProductTypeModel(id: 20, name: 'Rice', categoryId: 10)],
        units: [UnitModel(id: 30, name: 'Kilogram', symbol: 'kg')],
        products: [
          ProductModel(
            id: 40,
            name: 'Rice',
            productTypeId: 20,
            lots: [
              LotModel(
                id: 41,
                productId: 40,
                unitId: 30,
                quantity: 2.5,
                expirationDate: DateTime(2026, 1, 1),
              ),
            ],
          ),
        ],
      );

      final service = DataImportService(
        database: database,
        categoryRepository: categoryRepository,
        productTypeRepository: productTypeRepository,
        unitRepository: unitRepository,
        productRepository: productRepository,
        pickBackupFile: ({dialogTitle}) async => null,
      );

      await service.importBackup(backupPayload);

      final categories = await categoryRepository.getCategories();
      final productTypes = await productTypeRepository.getProductTypes();
      final units = await unitRepository.getUnits();
      final products = await productRepository.getProducts();

      expect(categories, hasLength(1));
      expect(categories.single.id, 10);
      expect(categories.single.name, 'Pantry');
      expect(productTypes, hasLength(1));
      expect(productTypes.single.id, 20);
      expect(productTypes.single.categoryId, 10);
      expect(units, hasLength(1));
      expect(units.single.id, 30);
      expect(products, hasLength(1));
      expect(products.single.id, 40);
      expect(products.single.productTypeId, 20);
      expect(products.single.lots, hasLength(1));
      expect(products.single.lots!.single.unitId, 30);
      expect(products.single.lots!.single.quantity, 2.5);
    },
  );

  test(
    'rolls back the restore when a repository fails during import',
    () async {
      final database = AppDatabase.forTesting(NativeDatabase.memory());
      addTearDown(database.close);

      final categoryRepository = CategoryRepository(database);
      final productTypeRepository = ProductTypeRepository(database);
      final productRepository = createProductRepository(database);

      await categoryRepository.createCategory('Original');

      final backupPayload = BackupImportPayload(
        categories: [CategoryModel(id: 1, name: 'Pantry')],
        productTypes: [ProductTypeModel(id: 2, name: 'Rice', categoryId: 1)],
        units: [UnitModel(id: 3, name: 'Kilogram', symbol: 'kg')],
        products: [
          ProductModel(
            id: 4,
            name: 'Rice',
            productTypeId: 2,
            lots: [
              LotModel(
                id: 5,
                productId: 4,
                unitId: 3,
                quantity: 1,
                expirationDate: null,
              ),
            ],
          ),
        ],
      );

      final service = DataImportService(
        database: database,
        categoryRepository: categoryRepository,
        productTypeRepository: productTypeRepository,
        unitRepository: FailingUnitRepository(database),
        productRepository: productRepository,
        pickBackupFile: ({dialogTitle}) async => null,
      );

      expect(
        () => service.importBackup(backupPayload),
        throwsA(isA<DataImportException>()),
      );

      final categories = await categoryRepository.getCategories();
      expect(categories, hasLength(1));
      expect(categories.single.name, 'Original');
    },
  );
}
